# Generated by Django 5.1.3 on 2024-12-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_enrollment_alter_subject_students'),
        ('users', '0002_alter_enrollment_mark_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
