site_name: Lumino
theme:
  name: null
  custom_dir: "cinder"

nav:
  - Requisitos: requisitos.md
  - Diseño: disenio.md
  - Implementación: implementacion.md
  - Pruebas: pruebas.md
  - Despliegue: despliegue.md
  - Manuales: manuales.md
  - Mantenimiento: mantenimiento.md
  - Conclusión: conclusion.md
