# Generated by Django 5.1.3 on 2025-01-13 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='enrolled', through='subjects.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
