# Generated by Django 5.1.3 on 2024-12-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
